package com.mediaworkspace.api.web;

import com.mediaworkspace.contracts.trace.TraceFields;
import jakarta.servlet.http.HttpServletRequest;
import org.slf4j.MDC;
import org.springframework.stereotype.Component;

import java.util.UUID;

/**
 * Per-request correlation values.
 *
 * <p>The request id is always generated by the server. A client may send {@code X-Request-Id} for
 * its own correlation, but the value is never adopted: a client that could choose the id could
 * attach its records to somebody else's chain, or make two unrelated requests look like one.
 *
 * <p>The trace id is different. It identifies a business chain that starts at upload creation and is
 * persisted with the upload, so it is restored from the stored resource rather than from a header.
 * The web layer leaves it alone; the application layer sets it once the resource is known.
 */
@Component
public class RequestContext {

    private static final ThreadLocal<String> REQUEST_ID = new ThreadLocal<>();

    /** Generates an id for this request and publishes it in the MDC and the response header. */
    public String begin(HttpServletRequest request) {
        String requestId = UUID.randomUUID().toString();
        REQUEST_ID.set(requestId);
        MDC.put(TraceFields.REQUEST_ID, requestId);
        return requestId;
    }

    public void end() {
        REQUEST_ID.remove();
        MDC.remove(TraceFields.REQUEST_ID);
    }

    /**
     * The current request's id.
     *
     * <p>Falls back to a fresh id when called outside a request, so an error body always has one
     * rather than a null.
     */
    public String currentRequestId() {
        String requestId = REQUEST_ID.get();
        return requestId != null ? requestId : MDC.get(TraceFields.REQUEST_ID);
    }

    /** Associates this thread with a persisted business chain for the rest of the request. */
    public void bindTrace(String traceId) {
        if (traceId != null && !traceId.isBlank()) {
            MDC.put(TraceFields.TRACE_ID, traceId);
        }
    }

    public String currentTraceId() {
        return MDC.get(TraceFields.TRACE_ID);
    }
}
