#!/usr/bin/env bash
#
# Idempotent host provisioning for the demo deployment (Ubuntu 24.04+/26.04, 2 vCPU, 2 GiB).
#
# Installs and configures MySQL 8.4 and a single-node KRaft Kafka broker, creates the demo and
# test schemas, and writes the runtime environment file. Secrets are generated on the host and
# written to the environment file with mode 0640; they are never echoed and never committed.
#
# Existing data owned by other projects is not touched: only the media_workspace databases,
# the /opt/media-workspace tree and the Kafka log directory named in deploy/kafka are created.
set -euo pipefail

DEPLOY_ROOT="${DEPLOY_ROOT:-/opt/media-workspace}"
CONFIG_DIR="$DEPLOY_ROOT/config"
ENV_FILE="$CONFIG_DIR/media-workspace.env"
KAFKA_VERSION="${KAFKA_VERSION:-3.9.2}"
KAFKA_SCALA_VERSION="${KAFKA_SCALA_VERSION:-2.13}"
# Apache's own archive host throttles this VM to a few KB/s; a mirror is used instead.
# Override KAFKA_MIRROR to build from a different source.
KAFKA_MIRROR="${KAFKA_MIRROR:-https://mirrors.huaweicloud.com/apache/kafka}"
KAFKA_HOME="/opt/kafka_${KAFKA_SCALA_VERSION}-${KAFKA_VERSION}"
KAFKA_LOG_DIR="$DEPLOY_ROOT/var/kafka-logs"

log() { printf '[provision] %s\n' "$*"; }

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "run with sudo" >&2
    exit 1
  fi
}

install_packages() {
  log "installing distribution packages"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq \
    openjdk-17-jdk-headless openjdk-21-jdk-headless \
    ffmpeg nginx mysql-server curl unzip zip jq rsync openssl >/dev/null
}

configure_mysql() {
  log "configuring MySQL (loopback only, 128M buffer pool)"
  install -m 0644 "$(dirname "$0")/../deploy/mysql/media-workspace.cnf" \
    /etc/mysql/mysql.conf.d/zz-media-workspace.cnf
  systemctl enable --now mysql >/dev/null 2>&1 || true
  systemctl restart mysql

  mkdir -p "$CONFIG_DIR"
  # The directory is traversable by the service account and by nobody else: the environment file
  # holds the database password and must not be world-readable.
  chmod 0750 "$CONFIG_DIR"
  chgrp ubuntu "$CONFIG_DIR" 2>/dev/null || true
  if [ ! -f "$ENV_FILE" ]; then
    umask 077
    cat > "$ENV_FILE" <<'ENVEOF'
# Generated by scripts/provision-host.sh. Not part of the repository.
DB_HOST=127.0.0.1
DB_PORT=3306
DB_NAME=media_workspace
DB_TEST_NAME=media_workspace_test
DB_USER=media_app
DB_PASSWORD=__GENERATED__
KAFKA_BOOTSTRAP=127.0.0.1:9092
# Empty for the demonstration deployment, so the topics carry exactly the names the contract
# specifies. The prefix exists so an integration run can share this broker without colliding with
# the demo topics or its consumer groups; setting it here would rename the demo topics instead.
KAFKA_TOPIC_PREFIX=
STORAGE_ROOT=/opt/media-workspace/var/storage
HTTP_PORT=8080
WORKER_HEALTH_PORT=8090
# Demonstration account passwords. Generated here, stored only in this file, never committed and
# never printed. The bootstrap command refuses to create an account without one.
MW_PASSWORD_OWNER=__PW1__
MW_PASSWORD_EDITOR=__PW2__
MW_PASSWORD_VIEWER=__PW3__
MW_PASSWORD_OUTSIDER=__PW4__
ENVEOF
    sed -i "s/__GENERATED__/${generated}/" "$ENV_FILE"
    for placeholder in __PW1__ __PW2__ __PW3__ __PW4__; do
      # Each account gets its own random password: reusing one would make a leak of any account a
      # leak of all four, and the acceptance cases rely on them being genuinely separate identities.
      sed -i "s/${placeholder}/$(openssl rand -hex 16)/" "$ENV_FILE"
    done
  fi
  # Top up keys added by a later version of this script, without touching the ones already there.
  # Rewriting the file would rotate the database password and lock the application out of its own
  # schema, so existing values are never regenerated.
  add_missing_key() {
    local key="$1" value="$2"
    grep -qE "^${key}=" "$ENV_FILE" || printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  }
  add_missing_key WORKER_HEALTH_PORT 8090
  add_missing_key MW_PASSWORD_OWNER "$(openssl rand -hex 16)"
  add_missing_key MW_PASSWORD_EDITOR "$(openssl rand -hex 16)"
  add_missing_key MW_PASSWORD_VIEWER "$(openssl rand -hex 16)"
  add_missing_key MW_PASSWORD_OUTSIDER "$(openssl rand -hex 16)"

  chmod 0640 "$ENV_FILE"
  chgrp ubuntu "$ENV_FILE" 2>/dev/null || true

  # shellcheck disable=SC1090
  . "$ENV_FILE"

  mysql --protocol=socket -uroot <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS \`${DB_TEST_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASSWORD}';
ALTER USER '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';
GRANT ALL PRIVILEGES ON \`${DB_TEST_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';
-- Integration runs create and drop their own schema per run so they can never touch demo data.
-- The pattern is escaped so 'mw_it_x' is the only shape it matches; the service account still has
-- no privilege on any other database on this server.
GRANT ALL PRIVILEGES ON \`mw\_it\_%\`.* TO '${DB_USER}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL
  log "MySQL ready: ${DB_NAME}, ${DB_TEST_NAME}, user ${DB_USER}"
}

install_kafka() {
  if [ ! -d "$KAFKA_HOME" ]; then
    log "installing Kafka ${KAFKA_VERSION}"
    local dist="kafka_${KAFKA_SCALA_VERSION}-${KAFKA_VERSION}.tgz"
    curl -fsSL --retry 3 --retry-delay 2 -o "/tmp/$dist" "${KAFKA_MIRROR}/${KAFKA_VERSION}/${dist}"
    tar -C /opt -xzf "/tmp/$dist"
    rm -f "/tmp/$dist"
  fi

  mkdir -p "$KAFKA_LOG_DIR"
  chown ubuntu:ubuntu "$KAFKA_LOG_DIR"
  # The shared media volume the API and the worker both mount, plus the run and log directories.
  install -d -o ubuntu -g ubuntu "$DEPLOY_ROOT/var/storage"
  install -d -o ubuntu -g ubuntu "$DEPLOY_ROOT/var/run"
  install -d -o ubuntu -g ubuntu "$DEPLOY_ROOT/var/logs/api" "$DEPLOY_ROOT/var/logs/worker"

  sed "s|@KAFKA_LOG_DIR@|${KAFKA_LOG_DIR}|" \
    "$(dirname "$0")/../deploy/kafka/server.properties" > "$KAFKA_HOME/config/kraft-media-workspace.properties"
  chown ubuntu:ubuntu "$KAFKA_HOME/config/kraft-media-workspace.properties"

  if [ ! -f "$KAFKA_LOG_DIR/meta.properties" ]; then
    log "formatting KRaft storage"
    cluster_id="$(sudo -u ubuntu "$KAFKA_HOME/bin/kafka-storage.sh" random-uuid)"
    sudo -u ubuntu "$KAFKA_HOME/bin/kafka-storage.sh" format \
      -t "$cluster_id" -c "$KAFKA_HOME/config/kraft-media-workspace.properties" >/dev/null
  fi

  cat > /etc/systemd/system/media-kafka.service <<UNIT
[Unit]
Description=media-workspace single-node Kafka (KRaft)
After=network-online.target

[Service]
Type=simple
User=ubuntu
Environment=KAFKA_HEAP_OPTS=-Xmx256m -Xms128m
Environment=LOG_DIR=${KAFKA_LOG_DIR}
ExecStart=${KAFKA_HOME}/bin/kafka-server-start.sh ${KAFKA_HOME}/config/kraft-media-workspace.properties
ExecStop=${KAFKA_HOME}/bin/kafka-server-stop.sh
Restart=on-failure
RestartSec=5
SuccessExitStatus=143
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable --now media-kafka >/dev/null 2>&1 || true
  systemctl restart media-kafka
  log "waiting for Kafka to accept connections"
  for _ in $(seq 1 60); do
    if "$KAFKA_HOME/bin/kafka-broker-api-versions.sh" --bootstrap-server 127.0.0.1:9092 >/dev/null 2>&1; then
      log "Kafka ready"
      return 0
    fi
    sleep 2
  done
  echo "Kafka did not become ready" >&2
  journalctl -u media-kafka -n 30 --no-pager >&2 || true
  return 1
}

create_topics() {
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  local p="${KAFKA_TOPIC_PREFIX:-mw}"
  local bs="${KAFKA_BOOTSTRAP:-127.0.0.1:9092}"
  for spec in "media.task.requested.v1:3" "media.task.result.v1:3" "media.events.dlq.v1:1"; do
    local name="${spec%%:*}" parts="${spec##*:}"
    "$KAFKA_HOME/bin/kafka-topics.sh" --bootstrap-server "$bs" --create --if-not-exists \
      --topic "${name}" --partitions "$parts" --replication-factor 1 >/dev/null
  done
  "$KAFKA_HOME/bin/kafka-topics.sh" --bootstrap-server "$bs" --list | sort
}

ensure_swap() {
  # Protection only. The measured resident footprint of the project fits in RAM; the extra swap
  # exists so that a build spike degrades throughput instead of triggering the OOM killer.
  # It is never relied on as capacity: see docs/runbook.md for the measured budget.
  local target_mb="${SWAP_TARGET_MB:-4096}"
  local current_mb
  current_mb="$(free -m | awk '/^Swap:/ {print $2}')"
  if [ "$current_mb" -ge "$target_mb" ]; then
    log "swap already ${current_mb} MiB"
    return 0
  fi
  local needed_mb=$((target_mb - current_mb))
  log "extending swap by ${needed_mb} MiB (OOM protection only)"
  if [ ! -f /swapfile-mw ]; then
    fallocate -l "${needed_mb}M" /swapfile-mw 2>/dev/null || dd if=/dev/zero of=/swapfile-mw bs=1M count="$needed_mb" status=none
    chmod 600 /swapfile-mw
    mkswap /swapfile-mw >/dev/null
  fi
  swapon /swapfile-mw 2>/dev/null || true
  grep -q '^/swapfile-mw ' /etc/fstab || echo '/swapfile-mw none swap sw 0 0' >> /etc/fstab
  sysctl -qw vm.swappiness=10
  free -m | awk '/^Swap:/ {printf "[provision] swap now %s MiB\n", $2}'
}

install_packages
configure_mysql
install_kafka
create_topics
ensure_swap
log "provisioning complete"
